Flask-Web-App-Tutorial-main 2/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

Flask-Web-App-Tutorial-main 2/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

Flask-Web-App-Tutorial-main 2/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

Flask-Web-App-Tutorial-main 2/website/views.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
from .models import Note
from . import db
import json

# Code from https://www.youtube.com/watch?v=dam0GPOAvVI&t=4299s
views = Blueprint('views', __name__)


# Define notes globally
notes = []

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)
    # Code from https://www.youtube.com/watch?v=dam0GPOAvVI&t=4299s


    #code from https://www.youtube.com/watch?v=31sSJjMoyw8

@views.route('/image-search')
def image_search():
    return render_template('image-search.html', user=current_user)

@views.route('/sticky')
def sticky():
    load_notes()
    return render_template('sticky-notes.html', user=current_user, notes=notes)

@views.route('/add_note', methods=['POST'])
def add_note():
    note_text = request.form['note_text']
    note_colour = request.form['note_colour']
    notes.append({'text': note_text, 'colour': note_colour})
    save_notes()
    return sticky()

# code from https://www.youtube.com/watch?v=31sSJjMoyw8
@views.route('/delete_note/<int:note_id>', methods=['GET', 'POST'])
def delete_note(note_id):
    if request.method == 'POST':
        if 0 <= note_id < len(notes):
            del notes[note_id]
            save_notes()
        return sticky()


# code from https://www.youtube.com/watch?v=31sSJjMoyw8
def load_notes():
    global notes
    try:
        with open('notes.json', 'r') as file:
            notes = json.load(file)
    except FileNotFoundError:
        notes = []

# code from https://www.youtube.com/watch?v=31sSJjMoyw8
def save_notes():
    with open('notes.json', 'w') as file:
        json.dump(notes, file, indent=4)

Flask-Web-App-Tutorial-main 2/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='base.css')}}"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon navbar-dark"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
<!--Code from https://www.youtube.com/watch?v=dam0GPOAvVI&t=4299s-->

Flask-Web-App-Tutorial-main 2/website/templates/home.html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Home</title>
    <meta name="description" content="" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='landing-page.css')}}"
  />
  </head>
  <body>
    <!--Nav-->
    <nav class="navbar navbar-expand-lg" style="background-color: #9f3d37">
      <div class="container">
        <a class="navbar-brand text-white fw-bold" href="{{ url_for('views.home') }}">ProdHub</a>
        <button
          class="navbar-toggler navbar-dark"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarScroll"
          aria-controls="navbarScroll"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul
            class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll"
            style="--bs-scroll-height: 200px"
          >
            <li class="nav-item">
              <a
                class="nav-link active text-white"
                aria-current="page"
                href="#index.html"
                >Home</a
              >
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle text-white"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Our Tools
              </a>
              <ul class="dropdown-menu">
             
                <li><a class="dropdown-item" href="{{ url_for('views.sticky') }}">Sticky Notes</a></li>

                <li><a class="dropdown-item" href="{{ url_for('views.image_search') }}">Image Search</a></li>

                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="/logout">Log Out</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="/logout" aria-disabled="true"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!--Nav-->

    <!-- Hero -->
    <section
      class="hero p-5 pt-lg-0 pt-lg-5 text-center text-sm-start text-white" 
      id="home"
    >
   
      <div class="container">
        <div
          class="d-sm-flex align-items-center justify-content-center text-center text-white"
        >
          <div>
            <h1 class="pt-5 hero-heading">
              Boost Your Productivity With Our Ultimate Productivity Companion
            </h1>
            <p class="">
            Our ultimate companion will help you in achieving your goals.
            </p>

          </div>
        </div>
      </div>
    </section>

    <!--hero-->


     <!-- Testimonials -->

     <section id="testimonials" class="p-5">
        <div class="container">
            <div class="container">

                <div class="row text-center  ">

                    <div class="col-sm-4 ">
                        <h3 class="font-weight-bold">1000+</h3>
                        <p>Happy Customers</p>
                    </div>

                    <div class="col-sm-4">
                        <h3 class="font-weight-bold ">50+</h3>
                        <p>New Tools Arriving</p>
                    </div>



                    <div class="col-sm-4">
                        <h3 class="font-weight-bold">3+</h3>
                        <p>Years of Operation</p>
                    </div>

                </div>
            </div>



    </section>



    <!-- Testimonials -->




    <!-- Quote -->

    <section class="quote p-4 pt-lg-0 pt-lg-5 text-center text-md-start">
        <div class="container">
            <div class="d-md-flex align-items-center justify-content-between">





                <div>
                    <h2 class="quote pt-5">The best way to predict<br> the future is to create it...</h2>

                    <p class="name">Peter Drucker</p>




                </div>


                <img class="img-fluid w-50 d-none d-sm-block pb-5" src="{{ url_for('static', filename='img/gym.jpg') }}" alt="Gym">

            </div>

        </div>

    </section>



    <!-- Quote -->





    <!--Some tools -->
    <section class=" what-we-do " id="services">


        <div class="container">
            <div class="row text-left">

                <h1 class="what-we-do-h1">Some tools</h1>

                <div class="col-md">
                    <h4 class="col-h4">Sticky Notes</h4>
                    <p class="col-text">Organise your thought with our Sticky Note app. Organize ideas, set reminders. </p>

                    <a href="{{ url_for('views.sticky') }}" class="card-cta">Visit Now</a>


                </div>




             



                <div class="col-md">
                    <h4 class="col-h4">Image Searcher</h4>
                    <p class="col-text">Find inspiration with our Image Search feature. Find and explore a vast array of images at your fingertips </p>
                    <a href="{{ url_for('views.image_search') }}" class="card-cta last">Visit Now</a>


                </div>


            </div>


        </div>
    </section>





    <!--Some tools -->

<!-- IMAGES-->
<div class="row no-gutters">
    <div class="col-md-6 g-0">
        <div class="leftside"></div>
    </div>

    <div class="col-md-6 g-0">
        <div class="rightside"></div>
    </div>
</div>
</div>
    
<!-- IMAGES-->


  <!--Footer -->

  <footer class="p-3 footer text-white text-center position-relative">


    <div class="container">


        <div class=" footer d-flex align-items-center justify-content-between text-center">
            <ul class="footer-ul">
                <a href="#"><i class="footer-icons bi bi-twitter text-light mx-1"></i></a>
                <a href="#"><i class="bi bi-facebook text-light mx-1"></i></a>
                <a href="#"><i class="bi bi-linkedin text-light mx-1"></i></a>
                <a href="#"><i class="bi bi-instagram text-light mx-1"></i></a>
            </ul>

            <a href="https://icons8.com/" target="new" class="attribution lead">https://icons8.com/</a>

            <a href="" class="arrow-up"><i class="bi bi-arrow-up-circle h1"></i></a>

        </div>
    </div>






</footer>

<!-- FOOTER -->

    
    <!-- Bootstrap JS and Popper.js scripts -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

Flask-Web-App-Tutorial-main 2/website/templates/image-search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Image Search</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='image-search.css')}}"
    />
  </head>
  <body>
    <!--Nav-->
    <nav class="navbar navbar-expand-lg" style="background-color: #9f3d37">
      <div class="container">
        <a
          class="navbar-brand text-white fw-bold"
          href="{{ url_for('views.home') }}"
          >ProdHub</a
        >
        <button
          class="navbar-toggler navbar-dark"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarScroll"
          aria-controls="navbarScroll"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul
            class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll"
            style="--bs-scroll-height: 200px"
          >
            <li class="nav-item">
              <a
                class="nav-link active text-white"
                aria-current="page"
                href="{{ url_for('views.home') }}"
                >Home</a
              >
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle text-white"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Our Tools
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{{ url_for('views.sticky') }}"
                    >Sticky Notes</a
                  >
                </li>

                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('views.image_search') }}"
                    >Image Search</a
                  >
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="/logout">Log Out</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" aria-disabled="true" href="/logout"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!--Nav-->
    <h1>Image Search</h1>
    <form id="search-form">
      <input type="text" id="search-box" placeholder="search here..." />
      <button>Search</button>
    </form>

    <div id="search-result">
      <div class="container"></div>
    </div>
    <button id="show-more-btn">Show More</button>

    <!--Footer -->

    <footer class="p-3 footer text-white text-center position-relative">
      <div class="container">
        <div
          class="footer d-flex align-items-center justify-content-between text-center"
        >
          <ul class="footer-ul">
            <a href="#"
              ><i class="footer-icons bi bi-twitter text-light mx-1"></i
            ></a>
            <a href="#"><i class="bi bi-facebook text-light mx-1"></i></a>
            <a href="#"><i class="bi bi-linkedin text-light mx-1"></i></a>
            <a href="#"><i class="bi bi-instagram text-light mx-1"></i></a>
          </ul>

          <a href="https://icons8.com/" target="new" class="attribution lead"
            >https://icons8.com/</a
          >

          <a href="" class="arrow-up"
            ><i class="bi bi-arrow-up-circle h1"></i
          ></a>
        </div>
      </div>
    </footer>

    <!-- FOOTER -->

    <script src="{{ url_for('static', filename='index.js') }}" defer></script>
    <!-- Bootstrap JS and Popper.js scripts -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

<!--SOME CODE FROM https://www.youtube.com/watch?v=E4znbZgUWzA&t=1s-->

Flask-Web-App-Tutorial-main 2/website/templates/sticky-notes.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sticky Notes</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <style>
      body {
        margin: 0;
        padding: 0;
        min-height: 100vh;
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      .header {
        background-color: #f2f2f2;
        padding: 20px;
        text-align: center;
      }

      .button {
        outline: none;
        border: none;
        color: white;
        font-weight: bold;
        background-color: #9f3d37;
        border-radius: 50px;
        padding: 15px 30px;
        -webkit-appearance: none;
      }

      @media screen and (max-width: 768px) {
        .button {
          outline: none;
          border: none;
          color: white;
          font-weight: bold;
          background-color: #9f3d37;
          border-radius: 50px;
          padding: 5px 5px;
          -webkit-appearance: none;
        }
      }

      @media screen and (max-width: 400px) {
        .button {
          outline: none;
          border: none;
          color: white;
          font-weight: bold;
          background-color: #9f3d37;
          border-radius: 50px;
          padding: 1px 1px;
          -webkit-appearance: none;
        }
      }

      .note-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: flex-start;
        max-width: 1600px;
        margin: 0 auto;
        padding: 20px;
        box-sizing: border-box;
      }

      input {
        border-radius: 50px;
        padding: 8px;
        outline: 0;
        border: solid 1px black;
      }

      .note {
        width: calc(20% - 20px);
        height: 300px;
        border: solid 1px black;
        margin: 0 10px 30px 10px;
        padding: 10px;
        overflow: auto;
        box-sizing: border-box;
      }

      .delete-icon {
        outline: none;
        border: none;
        background-color: transparent;
        font-size: 24px;
      }

      .yellow {
        background-color: #feff9c;
      }

      .lightblue {
        background-color: lightblue;
      }

      .pink {
        background-color: pink;
      }
      /*** FOOTER ***/
      .footer {
        background-color: #9f3d37;
        width: 100%;
        margin-top: auto; /* Push the footer to the bottom */
        padding: 20px 0; /* Add some padding for better visibility */
        color: white;
        text-align: center;
      }

      .arrow-up {
        color: white;
      }

      .arrow-up:hover {
        color: #fff;
      }

      .attribution {
        color: white;
        text-decoration: none;
        font-size: 14px;
      }

      .attribution:hover {
        color: #fff;
      }

      @media screen and (max-width: 768px) {
        .footer-ul {
          display: none;
        }
      }
    </style>
  </head>
  <body>
    <!--Nav-->
    <nav class="navbar navbar-expand-lg" style="background-color: #9f3d37">
      <div class="container">
        <a
          class="navbar-brand text-white fw-bold"
          href="{{ url_for('views.home') }}"
          >ProdHub</a
        >
        <button
          class="navbar-toggler navbar-dark"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarScroll"
          aria-controls="navbarScroll"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul
            class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll"
            style="--bs-scroll-height: 200px"
          >
            <li class="nav-item">
              <a
                class="nav-link active text-white"
                aria-current="page"
                href="{{ url_for('views.home') }}"
                >Home</a
              >
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle text-white"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Our Tools
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{{ url_for('views.sticky') }}"
                    >Sticky Notes</a
                  >
                </li>

                <li>
                  <a
                    class="dropdown-item"
                    href="{{ url_for('views.image_search') }}"
                    >Image Search</a
                  >
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="/logout">Log Out</a>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" aria-disabled="true" href="/logout"
                >Logout</a
              >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!--Nav-->

    <!--CONTENT-->
    <div class="content-container">
      <div class="header">
        <h1>Sticky Notes App</h1>
        <h3>Create a new note:</h3>
        <form action="/add_note" method="post">
          <input
            type="text"
            name="note_text"
            placeholder="Take a note..."
            style="color: gray"
          />
          <select name="note_colour">
            <option value="yellow">Yellow</option>
            <option value="pink">Pink</option>
            <option value="lightblue">Blue</option>
          </select>
          <button class="button" type="submit">Add</button>
        </form>
      </div>

      <div class="note-container">
        {% for note in notes %}
        <div class="note {{ note.colour }}">
          <p>{{ note.text }}</p>

          <form
            action="{{ url_for('views.delete_note', note_id=loop.index0) }}"
            method="post"
          >
            <button class="delete-icon" type="submit">
              <i class="bi bi-x"></i>
            </button>
          </form>
        </div>
        {% endfor %}
      </div>
    </div>
    <!--CONTENT-->

    <!--Footer -->

    <footer class="p-3 footer text-white text-center position-relative">
      <div class="container">
        <div
          class="footer d-flex align-items-center justify-content-between text-center"
        >
          <ul class="footer-ul">
            <a href="#"
              ><i class="footer-icons bi bi-twitter text-light mx-1"></i
            ></a>
            <a href="#"><i class="bi bi-facebook text-light mx-1"></i></a>
            <a href="#"><i class="bi bi-linkedin text-light mx-1"></i></a>
            <a href="#"><i class="bi bi-instagram text-light mx-1"></i></a>
          </ul>

          <a href="https://icons8.com/" target="new" class="attribution lead"
            >https://icons8.com/</a
          >

          <a href="" class="arrow-up"
            ><i class="bi bi-arrow-up-circle h1"></i
          ></a>
        </div>
      </div>
    </footer>

    <!-- FOOTER -->

    <!-- Bootstrap JS and Popper.js scripts -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>